{
  description = "Rust const x = 71 test";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      packages.${system}.default = pkgs.rustPlatform.buildRustPackage {
        pname = "const-71-rust";
        version = "0.1.0";
        
        src = pkgs.runCommand "const-71-rust-src" {} ''
          mkdir -p $out/src
          cat > $out/src/main.rs <<'EOF'
          fn main() {
              const X: i32 = 71;
              println!("x = {}", X);
          }
          EOF
          cat > $out/Cargo.toml <<'EOF'
          [package]
          name = "const-71-rust"
          version = "0.1.0"
          edition = "2021"
          EOF
          cat > $out/Cargo.lock <<'EOF'
          # This file is automatically @generated by Cargo.
          # It is not intended for manual editing.
          version = 3

          [[package]]
          name = "const-71-rust"
          version = "0.1.0"
          EOF
        '';
        
        cargoLock.lockFile = ./Cargo.lock;
      };
    };
}
