// 🔥 META-INTROSPECTOR MACRO LIBRARY
// Centralized macros for telemetry, symbol wrapping, and build-time code generation

/// Autodiscover build from collected data
#[macro_export]
macro_rules! autodiscover_build {
    () => {{
        // Load from our strace capture data
        let binaries = include_str!("../data/build_analysis/real_build_1768332029_binaries.json");
        let libraries = include_str!("../data/build_analysis/real_build_1768332029_libraries.json");
        let ldd_deps = include_str!("../data/build_analysis/real_build_1768332029_ldd_deps.json");
        
        (binaries, libraries, ldd_deps)
    }};
}

/// Define a binary to wrap with hints for discovery
#[macro_export]
macro_rules! define_binary {
    ($name:expr, nix_pattern: $pattern:expr) => {{
        // Find binary in nix store matching pattern
        // e.g., define_binary!("rustc", nix_pattern: "**/bin/rustc")
        compile_error!(concat!("DEFINE_BINARY:", $name, ":", $pattern));
    }};
}

/// Define a library to wrap with hints
#[macro_export]
macro_rules! define_library {
    ($name:expr, nix_pattern: $pattern:expr) => {{
        // Find .so in nix store matching pattern
        // e.g., define_library!("libc", nix_pattern: "**/libc.so.6")
        compile_error!(concat!("DEFINE_LIBRARY:", $name, ":", $pattern));
    }};
}

/// Map symbols from collected data
#[macro_export]
macro_rules! map_symbols {
    (from: $source:expr) => {{
        // Load symbols from JSON file we collected
        // e.g., map_symbols!(from: "data/build_analysis/real_build_1768332029_binaries.json")
        let data = include_str!($source);
        // build.rs will parse this and generate wrappers
        data
    }};
}

/// Bootstrap with autodiscovery
#[macro_export]
macro_rules! mkbootstrap {
    () => {{
        use std::sync::atomic::{AtomicUsize, Ordering};
        
        // Autodiscover from collected data
        let (binaries, libraries, ldd_deps) = autodiscover_build!();
        
        eprintln!("🔥 BOOTSTRAP: Autodiscovered build from strace data");
        eprintln!("📦 Binaries: {} bytes", binaries.len());
        eprintln!("📚 Libraries: {} bytes", libraries.len());
        eprintln!("🔗 LDD deps: {} bytes", ldd_deps.len());
        
        // Parse and initialize wrappers
        init_all_call_wrappers!();
    }};
}

/// Core telemetry wrapper
#[macro_export]
macro_rules! telemetry_wrap {
    ($name:expr, $func:expr) => {{
        let start = std::time::Instant::now();
        let result = $func;
        eprintln!("📊 {}: {:?}", $name, start.elapsed());
        result
    }};
}

/// Call telemetry with structured logging
#[macro_export]
macro_rules! call_telemetry {
    ($func_name:expr, $body:block) => {{
        let start = std::time::Instant::now();
        let result = $body;
        eprintln!("🔧 {}: {:?}", $func_name, start.elapsed());
        result
    }};
}

/// Wrap symbol - resolved at build time
#[macro_export]
macro_rules! wrap_symbol {
    ($symbol:expr) => {
        compile_error!(concat!("WRAP_SYMBOL:", $symbol));
    };
}

/// Initialize all wrappers - generated by build.rs
#[macro_export]
macro_rules! init_all_call_wrappers {
    () => {
        eprintln!("🚀 Wrappers initialized");
    };
}

/// Generic nix binary finder
#[macro_export]
macro_rules! find_nix_binary {
    ($pattern:expr) => {{
        // Search /nix/store for pattern
        // Returns first match or None
        std::fs::read_dir("/nix/store")
            .ok()
            .and_then(|entries| {
                entries
                    .filter_map(Result::ok)
                    .find(|e| e.path().to_str().map_or(false, |s| s.contains($pattern)))
                    .map(|e| e.path())
            })
    }};
}

/// Generic .so finder in nix
#[macro_export]
macro_rules! find_nix_library {
    ($name:expr) => {{
        // Search for .so file in nix store
        find_nix_binary!(concat!($name, ".so"))
    }};
}
