use anyhow::Result;
use std::path::{Path, PathBuf};
use tokio::fs;
use tracing::info;

pub async fn generate_wrapper(library_path: &Path, output_path: Option<PathBuf>) -> Result<PathBuf> {
    let library_info = crate::abi_extractor::extract_abi(library_path).await?;
    
    let wrapper_name = format!("lib{}_wrapper.so", 
        library_info.name.trim_start_matches("lib").trim_end_matches(".so"));
    
    let output_path = output_path.unwrap_or_else(|| {
        PathBuf::from(format!("./wrappers/{}", wrapper_name))
    });
    
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).await?;
    }
    
    // Generate C wrapper code
    let wrapper_code = generate_c_wrapper(&library_info);
    let c_file = output_path.with_extension("c");
    fs::write(&c_file, wrapper_code).await?;
    
    // Generate build script
    let build_script = generate_build_script(&library_info, &c_file, &output_path);
    let build_file = output_path.with_file_name("build_wrapper.sh");
    fs::write(&build_file, build_script).await?;
    
    // Make build script executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&build_file).await?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&build_file, perms).await?;
    }
    
    info!("✅ Generated wrapper files:");
    info!("   C code: {:?}", c_file);
    info!("   Build script: {:?}", build_file);
    info!("   Run: {:?}", build_file);
    
    Ok(output_path)
}

fn generate_c_wrapper(library_info: &crate::LibraryInfo) -> String {
    let mut code = String::new();
    
    // Header
    code.push_str(&format!(r#"
/*
 * Auto-generated wrapper for {}
 * Generated by nixso2wrap
 */

#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <string.h>
#include <time.h>
#include <pthread.h>
#include <unistd.h>
#include <sys/types.h>

// Telemetry structures
typedef struct {{
    char function_name[256];
    uint64_t timestamp_ns;
    pthread_t thread_id;
    pid_t process_id;
    void* args[16];
    void* return_value;
    uint64_t duration_ns;
}} call_record_t;

// Global state
static void* original_lib = NULL;
static FILE* telemetry_log = NULL;
static pthread_mutex_t log_mutex = PTHREAD_MUTEX_INITIALIZER;

// Initialization
__attribute__((constructor))
static void init_wrapper() {{
    // Load original library
    original_lib = dlopen("{}", RTLD_LAZY);
    if (!original_lib) {{
        fprintf(stderr, "Failed to load original library: %s\n", dlerror());
        exit(1);
    }}
    
    // Open telemetry log
    char log_path[512];
    snprintf(log_path, sizeof(log_path), "/tmp/wrapper_%s_%d.log", "{}", getpid());
    telemetry_log = fopen(log_path, "a");
    if (!telemetry_log) {{
        fprintf(stderr, "Failed to open telemetry log: %s\n", log_path);
    }}
    
    fprintf(stderr, "🔗 Wrapper initialized for {}\n");
    fprintf(stderr, "📊 Telemetry log: %s\n", log_path);
}}

// Cleanup
__attribute__((destructor))
static void cleanup_wrapper() {{
    if (original_lib) {{
        dlclose(original_lib);
    }}
    if (telemetry_log) {{
        fclose(telemetry_log);
    }}
}}

// Utility functions
static uint64_t get_timestamp_ns() {{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000000000ULL + ts.tv_nsec;
}}

static void log_call(const call_record_t* record) {{
    if (!telemetry_log) return;
    
    pthread_mutex_lock(&log_mutex);
    fprintf(telemetry_log, 
        "{{\"function\":\"%s\",\"timestamp\":%lu,\"thread\":%lu,\"pid\":%d,\"duration\":%lu}}\n",
        record->function_name,
        record->timestamp_ns,
        (unsigned long)record->thread_id,
        record->process_id,
        record->duration_ns
    );
    fflush(telemetry_log);
    pthread_mutex_unlock(&log_mutex);
}}

"#, 
        library_info.name,
        library_info.path.display(),
        library_info.name.replace(".", "_"),
        library_info.name
    ));
    
    // Generate wrapper functions for each exported symbol
    for symbol in &library_info.symbols {
        if matches!(symbol.symbol_type, crate::SymbolType::Function) {
            code.push_str(&generate_function_wrapper(symbol));
        }
    }
    
    code
}

fn generate_function_wrapper(symbol: &crate::SymbolInfo) -> String {
    let function_name = &symbol.name;
    
    // Generate a generic wrapper that can handle most function signatures
    format!(r#"
// Wrapper for {function_name}
void* {function_name}_wrapper(void* arg1, void* arg2, void* arg3, void* arg4, 
                              void* arg5, void* arg6, void* arg7, void* arg8) {{
    static void* (*original_func)(void*, void*, void*, void*, void*, void*, void*, void*) = NULL;
    
    // Get original function pointer
    if (!original_func) {{
        original_func = dlsym(original_lib, "{function_name}");
        if (!original_func) {{
            fprintf(stderr, "Failed to find function: {function_name}\n");
            return NULL;
        }}
    }}
    
    // Record call start
    call_record_t record;
    strncpy(record.function_name, "{function_name}", sizeof(record.function_name) - 1);
    record.timestamp_ns = get_timestamp_ns();
    record.thread_id = pthread_self();
    record.process_id = getpid();
    
    // Call original function
    uint64_t start_time = get_timestamp_ns();
    void* result = original_func(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    uint64_t end_time = get_timestamp_ns();
    
    // Record call end
    record.return_value = result;
    record.duration_ns = end_time - start_time;
    
    // Log the call
    log_call(&record);
    
    return result;
}}

// Alias for the original function name
void* {function_name}(void* arg1, void* arg2, void* arg3, void* arg4,
                      void* arg5, void* arg6, void* arg7, void* arg8) 
    __attribute__((alias("{function_name}_wrapper")));

"#, function_name = function_name)
}

fn generate_build_script(library_info: &crate::LibraryInfo, c_file: &Path, output_path: &Path) -> String {
    format!(r#"#!/bin/bash
# Auto-generated build script for {} wrapper

set -e

echo "🔨 Building wrapper for {}"

# Compile the wrapper
gcc -shared -fPIC \
    -o "{}" \
    "{}" \
    -ldl -lpthread \
    -Wl,--no-as-needed \
    -Wl,--export-dynamic

echo "✅ Wrapper built: {}"
echo ""
echo "Usage:"
echo "  export LD_PRELOAD=\"{}\""
echo "  your_program_here"
echo ""
echo "Or use with nixso2wrap telemetry shell:"
echo "  WRAPPER_LIB=\"{}\" nixso2wrap-shell your_program"

"#, 
    library_info.name,
    library_info.name,
    output_path.display(),
    c_file.display(),
    output_path.display(),
    output_path.display(),
    output_path.display()
)
}
